# Site settings
title: lwPan's blog
nickname: lwPan @ Blog 
email: coderlwpan@gmail.com
description: code 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.lwpan.com" # the base hostname & protocol for your site
twitter_username: lwPan
github_username: lwPan

# Build settings
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
