# Site settings
title: 一起跳舞 
email: coderlwpan@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lwpann.github.io" # the base hostname & protocol for your site
twitter_username: lwpan
github_username:  lwpan

# Build settings
markdown: kramdown
